authentication.generate_token:
    path: /auth/token/generate
    controller: 'App\Controller\Authentication\GenerateTokenController::generateAction'
    methods: ['POST']
    defaults:
        _secured: true

authentication.lookup:
    path: /auth/token/lookup/{token}
    controller: 'App\Controller\Authentication\LookupTokenController::handle'
    methods: ['GET']
    defaults:
        _secured: true

authentication.clear_expired_tokens:
    path: /jobs/token/expired/clear
    controller: 'App\Controller\Authentication\ClearExpiredTokensController::clearAction'
    methods: ['GET']
    defaults:
        _secured: true
