App\Domain\Storage\Entity\StoredFile:
    type: entity
    table: file_registry

    id:
        id:
            type: integer
            generator:
                strategy: IDENTITY

    fields:
        fileName:
            type: string
            length: 254
            column: fileName

        contentHash:
            type: string
            length: 64
            column: contentHash

        dateAdded:
            type: datetime_immutable
            column: dateAdded

        mimeType:
            type: string
            length: 48
            column: mimeType

        password:
            type: string
            length: 254
            column: password

    manyToMany:
        tags:
            targetEntity: Tag
            inversedBy: files
            joinTable:
                name: file_tags
                joinColumns:
                    file_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    tag_id:
                        referencedColumnName: id
