App\Domain\Authentication\Entity\Token:
    type: entity
    table: tokens

    id:
        id:
            type: guid
            unique: true
            nullable: false
            id: true
            length: 36
            generator:
                strategy: UUID

    fields:
        roles:
            type: json

        data:
            type: json

        expirationDate:
            type: datetime_immutable
            column: expiration_date

        creationDate:
            type: datetime_immutable
            column: creation_date
